In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

In [2]:
csv_name = "raw_dog_traits_table_2013_2025.csv"

for base_dir in [Path.cwd(), *Path.cwd().parents]:
    csv_path = base_dir / "data" / "raw" / csv_name
    if csv_path.exists():
        break
else:
    raise FileNotFoundError(
        f"Could not find {csv_name} under a data/raw directory starting from {Path.cwd()}"
    )

In [3]:
raw_df = pd.read_csv(csv_path)
raw_df

,Breed,Group,2013 Rank,2014 Rank,2015 Rank,2016 Rank,2017 Rank,2018 Rank,2019 Rank,2020 Rank,...,Coat Type,Coat Length,Openness To Strangers,Playfulness Level,Watchdog/Protective Nature,Adaptability Level,Trainability Level,Energy Level,Barking Level,Mental Stimulation Needs
0,Affenpinscher,Toy Group,143.0,144.0,136.0,149.0,147.0,148.0,152.0,163.0,...,Wiry,Short; Medium,5,3,3,4,3,3,3,3
1,Afghan Hound,Hound Group,95.0,98.0,100.0,113.0,93.0,113.0,113.0,122.0,...,Silky,Long,3,3,3,3,1,4,3,3
2,Airedale Terrier,Terrier Group,56.0,57.0,53.0,55.0,55.0,60.0,61.0,62.0,...,Wiry,Short; Medium,3,3,5,3,3,3,3,3
3,Akita,Working Group,45.0,46.0,46.0,46.0,47.0,47.0,47.0,48.0,...,Double,Medium,2,3,5,3,3,4,2,3
4,Alaskan Malamute,Working Group,57.0,54.0,54.0,59.0,59.0,58.0,65.0,65.0,...,Double,Medium,3,3,4,3,5,4,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,Wire Fox Terrier,Terrier Group,96.0,95.0,94.0,101.0,99.0,101.0,101.0,104.0,...,Wiry; Double,Medium,5,4,4,4,4,4,4,4
198,Wirehaired Pointing Griffon,Sporting Group,80.0,76.0,66.0,66.0,65.0,65.0,63.0,63.0,...,Wiry; Double,Medium,5,4,3,4,5,5,3,5
199,Wirehaired Vizsla,Sporting Group,NaN,107.0,156.0,157.0,155.0,167.0,147.0,155.0,...,Wiry,Short,5,5,3,4,5,5,3,5
200,Xoloitzcuintli,Non-Sporting Group,139.0,142.0,135.0,139.0,143.0,140.0,139.0,131.0,...,Hairless; Smooth,Short,3,4,3,4,4,4,3,4
201,Yorkshire Terrier,Toy Group,6.0,6.0,7.0,9.0,9.0,10.0,12.0,13.0,...,Silky,Long,5,4,5,5,4,4,4,4

In [4]:
breed_group = raw_df[['Breed', 'Group']]
breed_group

                           Breed               Group
0                  Affenpinscher           Toy Group
1                   Afghan Hound         Hound Group
2               Airedale Terrier       Terrier Group
3                          Akita       Working Group
4               Alaskan Malamute       Working Group
..                           ...                 ...
197             Wire Fox Terrier       Terrier Group
198  Wirehaired Pointing Griffon      Sporting Group
199            Wirehaired Vizsla      Sporting Group
200               Xoloitzcuintli  Non-Sporting Group
201            Yorkshire Terrier           Toy Group

[202 rows x 2 columns]

In [5]:
rank_cols = [f'{year} Rank' for year in range(2013, 2026)]
breed_rank = raw_df[['Breed', *rank_cols]]
breed_rank

,Breed,2013 Rank,2014 Rank,2015 Rank,2016 Rank,2017 Rank,2018 Rank,2019 Rank,2020 Rank,2021 Rank,2022 Rank,2023 Rank,2024 Rank,2025 Rank
0,Affenpinscher,143.0,144.0,136.0,149.0,147.0,148.0,152.0,163.0,159.0,148.0,162.0,162.0,153
1,Afghan Hound,95.0,98.0,100.0,113.0,93.0,113.0,113.0,122.0,114.0,117.0,111.0,110.0,117
2,Airedale Terrier,56.0,57.0,53.0,55.0,55.0,60.0,61.0,62.0,62.0,65.0,67.0,64.0,70
3,Akita,45.0,46.0,46.0,46.0,47.0,47.0,47.0,48.0,52.0,55.0,58.0,59.0,62
4,Alaskan Malamute,57.0,54.0,54.0,59.0,59.0,58.0,65.0,65.0,68.0,67.0,71.0,79.0,81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,Wire Fox Terrier,96.0,95.0,94.0,101.0,99.0,101.0,101.0,104.0,99.0,102.0,104.0,113.0,107
198,Wirehaired Pointing Griffon,80.0,76.0,66.0,66.0,65.0,65.0,63.0,63.0,60.0,57.0,57.0,51.0,51
199,Wirehaired Vizsla,NaN,107.0,156.0,157.0,155.0,167.0,147.0,155.0,144.0,142.0,142.0,159.0,130
200,Xoloitzcuintli,139.0,142.0,135.0,139.0,143.0,140.0,139.0,131.0,119.0,116.0,122.0,119.0,123
201,Yorkshire Terrier,6.0,6.0,7.0,9.0,9.0,10.0,12.0,13.0,13.0,13.0,13.0,11.0,13

In [9]:
breed_traits = raw_df[["Breed", *raw_df.columns[17:]]]
breed_traits

,Breed,Good With Young Children,Good With Other Dogs,Shedding Level,Coat Grooming Frequency,Drooling Level,Coat Type,Coat Length,Openness To Strangers,Playfulness Level,Watchdog/Protective Nature,Adaptability Level,Trainability Level,Energy Level,Barking Level,Mental Stimulation Needs
0,Affenpinscher,3,3,3,3,1,Wiry,Short; Medium,5,3,3,4,3,3,3,3
1,Afghan Hound,3,3,1,4,1,Silky,Long,3,3,3,3,1,4,3,3
2,Airedale Terrier,3,3,1,3,1,Wiry,Short; Medium,3,3,5,3,3,3,3,3
3,Akita,3,1,3,3,1,Double,Medium,2,3,5,3,3,4,2,3
4,Alaskan Malamute,3,3,3,3,1,Double,Medium,3,3,4,3,5,4,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,Wire Fox Terrier,5,3,2,3,2,Wiry; Double,Medium,5,4,4,4,4,4,4,4
198,Wirehaired Pointing Griffon,5,3,3,2,3,Wiry; Double,Medium,5,4,3,4,5,5,3,5
199,Wirehaired Vizsla,5,3,3,1,2,Wiry,Short,5,5,3,4,5,5,3,5
200,Xoloitzcuintli,3,3,1,1,1,Hairless; Smooth,Short,3,4,3,4,4,4,3,4
201,Yorkshire Terrier,5,3,1,5,1,Silky,Long,5,4,5,5,4,4,4,4